# Generated by Django 4.2.2 on 2023-06-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='des1',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name1',
            new_name='name',
        ),
    ]
